url: "https://docs.google.com/spreadsheets/d/e/2PACX-1vQ8E9zQtIlJyqRuIh8Rd3453ugezaZYz1ODuBkPuhI8NhIOIp8i5TAa6okzHZxItQ6sZl0Gybrf2IeJ/pub?gid=0&single=true&output=csv"

googlesheets: "https://docs.google.com/spreadsheets/d/1BZUBm195VifFG6EiRQvntg7NZfRy0mXfQ9dIb2zdbWs/edit#gid=0"
